<?php
/**
 * Central content/data for the Pramit Sarkar — AI Solutions Agency site.
 * Everything the pages render is defined here so content lives in one place.
 */

/**
 * Inline an SVG brand logo from assets/img/<dir> (default "tech") and tint it with a brand color.
 * The single-color logo paths inherit `fill` from the <svg> element, so we
 * inject the color there. Falls back to an empty string if the file is missing.
 */
if (!function_exists('render_svg_logo')) {
    function render_svg_logo(string $logo, string $color = 'currentColor', string $dir = 'tech'): string
    {
        $file = dirname(__DIR__) . '/assets/img/' . basename($dir) . '/' . basename($logo) . '.svg';
        if (!is_file($file)) {
            return '';
        }
        $svg  = file_get_contents($file);
        $fill = htmlspecialchars($color, ENT_QUOTES);
        return preg_replace(
            '/<svg /',
            '<svg fill="' . $fill . '" aria-hidden="true" focusable="false" ',
            $svg,
            1
        );
    }
}

/* ---------- Site meta ---------- */
$SITE = [
    'name'        => 'Pramit Sarkar',
    'title'       => 'Pramit Sarkar — AI Solutions Agency',
    'description' => 'I build intelligent AI systems, automations, and custom software that save businesses time, cut costs, and increase revenue. Based in India, working globally.',
    'url'         => 'https://pramitsarkar-ai.onrender.com',
    'email'       => 'pramitsarkar.work@gmail.com',
    'phone'       => '+919474322424',
    'calendly'    => 'https://calendly.com/pramitsarkar-work',
    'whatsapp'    => 'https://wa.me/919474322424',
    'github'      => 'https://github.com/Curious-Coderr',
    'linkedin'    => 'https://www.linkedin.com/in/pramit-sarkar1/',
];

/* ---------- Navigation ---------- */
$NAV_LINKS = [
    ['label' => 'About',    'href' => '#about'],
    ['label' => 'Services', 'href' => '#services'],
    ['label' => 'Work',     'href' => '#projects'],
    ['label' => 'Process',  'href' => '#process'],
    ['label' => 'Tech',     'href' => '#tech-stack'],
    ['label' => 'FAQ',      'href' => '#faq'],
    ['label' => 'Contact',  'href' => '#contact'],
];

/* ---------- Hero tech logos (marquee) ---------- */
$TECH_LOGOS = [
    ['name' => 'OpenAI',     'logo' => 'openai',     'color' => '#10A37F'],
    ['name' => 'Gemini',     'logo' => 'gemini',     'color' => '#8E75FF'],
    ['name' => 'Claude',     'logo' => 'claude',     'color' => '#D97757'],
    ['name' => 'n8n',        'logo' => 'n8n',        'color' => '#EA4B71'],
    ['name' => 'Python',     'logo' => 'python',     'color' => '#4B8BBE'],
    ['name' => 'PHP',        'logo' => 'php',        'color' => '#A5A6F6'],
    ['name' => 'WordPress',  'logo' => 'wordpress',  'color' => '#4A90C2'],
    ['name' => 'Docker',     'logo' => 'docker',     'color' => '#2496ED'],
    ['name' => 'MySQL',      'logo' => 'mysql',      'color' => '#4FA0D8'],
    ['name' => 'Cloudflare', 'logo' => 'cloudflare', 'color' => '#F38020'],
    ['name' => 'Git',        'logo' => 'git',        'color' => '#F05032'],
];

/* ---------- Headline stats ---------- */
$STATS = [
    ['value' => 12,  'suffix' => '+',  'label' => 'Systems shipped'],
    ['value' => 14,  'suffix' => '',   'label' => 'Industries served'],
    ['value' => 24,  'suffix' => 'h',  'label' => 'Response time'],
    ['value' => 100, 'suffix' => '%',  'label' => 'Client ownership'],
];

/* ---------- About credentials ---------- */
$CREDENTIALS = [
    ['icon' => 'code',           'text' => 'AI & Automation Systems Builder'],
    ['icon' => 'globe',          'text' => 'Serving US, UK, and India-based clients'],
];

/* ---------- About panel: industries I work in ---------- */
$ABOUT_INDUSTRIES = [
    ['icon' => 'heart-pulse',   'name' => 'Healthcare'],
    ['icon' => 'building-2',    'name' => 'Real Estate'],
    ['icon' => 'scale',         'name' => 'Legal'],
    ['icon' => 'shopping-cart', 'name' => 'Ecommerce'],
    ['icon' => 'briefcase',     'name' => 'Professional Services'],
    ['icon' => 'layout-grid',   'name' => 'SaaS'],
];

/* ---------- Services ---------- */
$SERVICES = [
    ['icon' => 'bot',         'title' => 'AI Chatbots & Agents',      'color' => '#6366F1', 'description' => 'Intelligent chatbots trained on your business content — answer FAQs, qualify leads, and handle support 24/7.'],
    ['icon' => 'zap',         'title' => 'AI Automation Systems',     'color' => '#3B82F6', 'description' => 'End-to-end automation pipelines using n8n, OpenAI, and Gemini to eliminate repetitive work across your operations.'],
    ['icon' => 'bar-chart-3', 'title' => 'Custom CRM Development',    'color' => '#22D3EE', 'description' => 'Purpose-built CRM systems that match your exact sales pipeline — no bloat, no unnecessary features, fully owned.'],
    ['icon' => 'workflow',    'title' => 'Business Automation',       'color' => '#8B5CF6', 'description' => 'Connect your existing tools and automate workflows across email, CRM, invoicing, and reporting.'],
    ['icon' => 'globe',       'title' => 'Custom Web Development',    'color' => '#10B981', 'description' => 'High-performance, SEO-optimised websites and web apps built with Next.js, TypeScript, and Tailwind CSS.'],
    ['icon' => 'shopping-bag','title' => 'WordPress & WooCommerce',   'color' => '#F59E0B', 'description' => 'Custom WordPress builds and WooCommerce stores — fast, conversion-optimised, and fully managed.'],
    ['icon' => 'plug',        'title' => 'API Integration',           'color' => '#EC4899', 'description' => 'Connect any two systems. Custom API integrations, webhooks, and middleware that keep your data in sync.'],
    ['icon' => 'git-branch',  'title' => 'Workflow Automation',       'color' => '#14B8A6', 'description' => 'Map, streamline, and automate your core business processes — from lead capture to invoicing to delivery.'],
    ['icon' => 'search',      'title' => 'SEO & Technical SEO',       'color' => '#F97316', 'description' => 'Technical SEO audits, Core Web Vitals fixes, schema markup, and content strategy to rank and convert.'],
    ['icon' => 'trending-up', 'title' => 'Digital Transformation',    'color' => '#A78BFA', 'description' => 'Full-stack consulting to move your business from fragmented tools to a unified, AI-powered operating system.'],
];

/* ---------- Process steps ---------- */
$PROCESS = [
    ['number' => '01', 'title' => 'Discovery', 'icon' => 'search',    'color' => '#3B82F6', 'description' => 'We map your operations, identify where AI and automation create the highest leverage, and define a clear scope with measurable outcomes.'],
    ['number' => '02', 'title' => 'Design',    'icon' => 'pen-tool',  'color' => '#6366F1', 'description' => 'System architecture, workflow diagrams, data flow, and UI prototypes — everything agreed and signed off before a single line of code is written.'],
    ['number' => '03', 'title' => 'Build',     'icon' => 'code-2',    'color' => '#8B5CF6', 'description' => 'Iterative development with weekly check-ins. You see real progress every week, not a big reveal after months of silence.'],
    ['number' => '04', 'title' => 'Deploy',    'icon' => 'rocket',    'color' => '#A78BFA', 'description' => 'Launch to production with proper staging, testing, and documentation. Your team gets trained on anything they need to operate it.'],
    ['number' => '05', 'title' => 'Support',   'icon' => 'life-buoy', 'color' => '#22D3EE', 'description' => 'Post-launch monitoring, iteration based on real usage data, and ongoing support so the system keeps running and improving over time.'],
];

/* ---------- Tech stack (grouped by category, with brand logos) ---------- */
$TECH_STACK = [
    ['category' => 'AI', 'items' => [
        ['name' => 'OpenAI',      'logo' => 'openai',      'color' => '#10A37F'],
        ['name' => 'Gemini',      'logo' => 'gemini',      'color' => '#8E75FF'],
        ['name' => 'Claude',      'logo' => 'claude',      'color' => '#D97757'],
        ['name' => 'Deepseek',    'logo' => 'deepseek',    'color' => '#4D6BFE'],
    ]],
    ['category' => 'Automation', 'items' => [
        ['name' => 'n8n',         'logo' => 'n8n',         'color' => '#EA4B71'],
        ['name' => 'Make',        'logo' => 'make',        'color' => '#A855F7'],
        ['name' => 'Antigravity', 'logo' => 'antigravity', 'color' => '#7C9CFF'],
        ['name' => 'Junie',       'logo' => 'junie',       'color' => '#C15CFF'],
        ['name' => 'Opencode',    'logo' => 'opencode',    'color' => '#22D3EE'],
    ]],
    ['category' => 'Languages', 'items' => [
        ['name' => 'Python',      'logo' => 'python',      'color' => '#4B8BBE'],
        ['name' => 'JavaScript',  'logo' => 'javascript',  'color' => '#F7DF1E'],
        ['name' => 'PHP',         'logo' => 'php',         'color' => '#A5A6F6'],
    ]],
    ['category' => 'Frontend', 'items' => [
        ['name' => 'HTML',        'logo' => 'html',        'color' => '#E34F26'],
        ['name' => 'CSS',         'logo' => 'css',         'color' => '#3B9EDD'],
    ]],
    ['category' => 'CMS', 'items' => [
        ['name' => 'WordPress',   'logo' => 'wordpress',   'color' => '#4A90C2'],
        ['name' => 'WooCommerce', 'logo' => 'woocommerce', 'color' => '#B368B0'],
    ]],
    ['category' => 'Database', 'items' => [
        ['name' => 'MySQL',       'logo' => 'mysql',       'color' => '#4FA0D8'],
        ['name' => 'SQLite',      'logo' => 'sqlite',      'color' => '#57B6E5'],
    ]],
    ['category' => 'Deployment', 'items' => [
        ['name' => 'Docker',      'logo' => 'docker',      'color' => '#2496ED'],
        ['name' => 'Ubuntu',      'logo' => 'ubuntu',      'color' => '#E95420'],
        ['name' => 'VPS',         'logo' => 'vps',         'color' => '#34D399'],
        ['name' => 'Cloudflare',  'logo' => 'cloudflare',  'color' => '#F38020'],
        ['name' => 'Cpanel',      'logo' => 'cpanel',      'color' => '#FF6C2C'],
        ['name' => 'Hpanel',      'logo' => 'hpanel',      'color' => '#7C5CFF'],
    ]],
    ['category' => 'Version Control', 'items' => [
        ['name' => 'Git',         'logo' => 'git',         'color' => '#F05032'],
    ]],
];

/* ---------- Industries ---------- */
$INDUSTRIES = [
    'Healthcare', 'Real Estate', 'Legal', 'Retail', 'Restaurants',
    'Agencies', 'Ecommerce', 'Education', 'Local Services', 'Finance',
    'Logistics', 'SaaS', 'Consulting', 'Construction',
];

$INDUSTRY_COLORS = [
    ['bg' => 'rgba(59,130,246,0.1)',  'border' => 'rgba(59,130,246,0.2)',  'text' => '#60A5FA'],
    ['bg' => 'rgba(99,102,241,0.1)',  'border' => 'rgba(99,102,241,0.2)',  'text' => '#818CF8'],
    ['bg' => 'rgba(34,211,238,0.08)', 'border' => 'rgba(34,211,238,0.15)', 'text' => '#22D3EE'],
    ['bg' => 'rgba(16,185,129,0.08)', 'border' => 'rgba(16,185,129,0.15)', 'text' => '#34D399'],
    ['bg' => 'rgba(245,158,11,0.08)', 'border' => 'rgba(245,158,11,0.15)', 'text' => '#FBBF24'],
    ['bg' => 'rgba(236,72,153,0.08)', 'border' => 'rgba(236,72,153,0.15)', 'text' => '#F472B6'],
    ['bg' => 'rgba(139,92,246,0.1)',  'border' => 'rgba(139,92,246,0.2)',  'text' => '#A78BFA'],
];

/* ---------- FAQ ---------- */
$FAQS = [
    ['q' => 'What types of projects do you take on?', 'a' => "AI systems, automation pipelines, CRM development, custom web apps, WordPress/WooCommerce builds, API integrations, and workflow automation. If the problem involves removing manual work or adding intelligence to a business process, it's in scope."],
    ['q' => "What's a typical project timeline?", 'a' => "Simple automations: 1–2 weeks. Custom web builds: 3–4 weeks. AI agents and CRMs: 4–8 weeks. Complex multi-phase systems: 8–12+ weeks. I'll give you a specific timeline after a discovery call — not a generic estimate."],
    ['q' => 'How does pricing work?', 'a' => "Project-based pricing, scoped after discovery. I don't charge by the hour — you get a fixed price for a defined outcome. Typical engagements range from ₹50,000 to ₹5,00,000 depending on complexity. Retainer support available post-launch."],
    ['q' => "Can you automate a process I'm currently doing manually?", 'a' => "Almost certainly yes — if you can describe the steps you take manually, I can map out an automation. The best candidates are repetitive processes with clear rules: data entry, email follow-ups, report generation, lead qualification, invoicing."],
    ['q' => 'What AI models do you work with?', 'a' => "OpenAI (GPT-4o, GPT-4o mini), Google Gemini (2.5 Flash, 2.5 Pro), Anthropic Claude, and open-source models via Ollama for self-hosted deployments. I pick the right model for the task based on cost, latency, and accuracy requirements."],
    ['q' => 'Do you provide post-launch support?', 'a' => "Yes — all projects include a post-launch support period. Ongoing retainer support is available for monitoring, maintenance, and iteration. The goal is a system that keeps working and improving, not a handover and goodbye."],
    ['q' => 'Can I see your work before engaging?', 'a' => "Yes — the project case studies on this site give you a real look at how I think about problems and build solutions. You can also book a discovery call to discuss a specific problem and get my honest assessment of what's possible."],
];

/* ---------- Contact form options ---------- */
$BUDGET_RANGES = [
    'Under ₹50,000',
    '₹50,000 – ₹1,50,000',
    '₹1,50,000 – ₹5,00,000',
    '₹5,00,000+',
    "Let's discuss",
];

$PROJECT_TYPES = [
    'AI Automation System',
    'AI Chatbot / Agent',
    'Custom CRM',
    'Business Automation',
    'Custom Web Development',
    'WordPress / WooCommerce',
    'API Integration',
    'Digital Transformation',
    'Other',
];

/* ---------- Contact sidebar links ---------- */
$CONTACT_LINKS = [
    ['logo' => 'calendly', 'label' => 'Book a Discovery Call', 'sub' => '30 min, no obligation',   'href' => $SITE['calendly'],                              'color' => '#006BFF'],
    ['logo' => 'gmail',    'label' => $SITE['email'],          'sub' => 'Direct email',            'href' => 'mailto:' . $SITE['email'],                     'color' => '#EA4335'],
    ['logo' => 'whatsapp', 'label' => 'WhatsApp',              'sub' => 'Quick questions welcome', 'href' => $SITE['whatsapp'],                              'color' => '#25D366'],
    ['logo' => 'linkedin', 'label' => 'LinkedIn',              'sub' => 'Connect professionally',  'href' => $SITE['linkedin'],                              'color' => '#0A66C2'],
    ['logo' => 'github',   'label' => 'GitHub',                'sub' => 'See open-source work',    'href' => $SITE['github'],                                'color' => '#ffffff'],
];

/* ---------- Footer links ---------- */
$FOOTER_NAV = [
    ['label' => 'About',    'href' => '#about'],
    ['label' => 'Services', 'href' => '#services'],
    ['label' => 'Work',     'href' => '#projects'],
    ['label' => 'Process',  'href' => '#process'],
    ['label' => 'FAQ',      'href' => '#faq'],
    ['label' => 'Contact',  'href' => '#contact'],
];

$SOCIAL_LINKS = [
    ['logo' => 'github',   'label' => 'GitHub',   'href' => $SITE['github'],               'color' => '#ffffff'],
    ['logo' => 'linkedin', 'label' => 'LinkedIn', 'href' => $SITE['linkedin'],             'color' => '#0A66C2'],
    ['logo' => 'gmail',    'label' => 'Email',    'href' => 'mailto:' . $SITE['email'],    'color' => '#EA4335'],
    ['logo' => 'whatsapp', 'label' => 'WhatsApp', 'href' => $SITE['whatsapp'],             'color' => '#25D366'],
];

/* ---------- Projects ---------- */
$PROJECTS = [
    [
        'slug'      => 'mediascape-digital-marketing-agency',
        'featured'  => true,
        'priority'  => 20,
        'title'     => 'Mediascape — Digital Marketing Agency',
        'category'  => 'Web',
        'status'    => 'Live',
        'client'    => 'Mediascape',
        'liveUrl'   => 'https://mediascape.co.in',
        'cover'     => '',
        'summary'   => 'Full agency website for Mediascape — India\'s Leading Digital Marketing Agency, URF Award winner — showcasing 6 service verticals, a tiered Social Media pricing system (₹5,999–₹29,999), a live custom plan builder, website design packages, client testimonials, and a project portfolio.',
        'problem'   => 'Mediascape needed a website that could do more than look good — it had to clearly communicate 9 distinct service offerings, present 7 pricing tiers without overwhelming visitors, and let potential clients build their own custom service package in real time, all while establishing the agency\'s credibility (URF Award, 10,000+ projects, 7 years in business).',
        'solution'  => 'Built a dark gold-themed agency site on WordPress that leads with authority ("India\'s Leading Digital Marketing Agency — Recognized with the URF Award"). Structured the homepage into clear service cards (Social Media Marketing, Website Development, App Development, Brand Identity, SEO Optimization, Influencer Marketing, Affiliate Management, Wedding Management, Event Management). Built an interactive "Create Your Custom Plan" configurator where visitors toggle individual services (FB/IG Management, SEO, Graphics, Reels, Drone Shoot, Logo Design, Meta Ads Budget) and see a live total price. Added a full Social Media Packages pricing table (Starter ₹5,999 → Diamond ₹29,999) and a Website Design Packages section (Portfolio ₹10,499 / E-Commerce ₹14,999 / Ultimate ₹19,999). Integrated a client testimonial carousel, a "Projects, We Are Proud Of" portfolio gallery, a PROCESS section, stats counters, FAQ accordion, and a "Let\'s Transform Your Brand Today" CTA. Added Brochure download button and WhatsApp/email contact details in footer.',
        'features'  => [
            'Dark gold premium brand theme with animated hero',
            '9 service verticals — Social Media, Web Dev, App Dev, Brand Identity, SEO, Influencer, Affiliate, Wedding, Event Management',
            'Social Media Packages table — 7 tiers: Starter ₹5,999 → Diamond ₹29,999',
            'Interactive "Create Your Custom Plan" configurator with live price calculator',
            'Website Design Packages — Portfolio ₹10,499 / E-Commerce ₹14,999 / Ultimate ₹19,999',
            '"Projects, We Are Proud Of" portfolio gallery section',
            'Stats counters — 10,000+ Successful Projects, 7Y in Business, 100+ Happy Clients, 200k Ads Spent',
            'Client testimonials carousel with 5-star reviews',
            'PROCESS section — Discovery → Planning → Design → Posting to Social Media',
            'FAQ accordion with 6 common questions',
            'Brochure download CTA button',
            '"Let\'s Transform Your Brand Today" animated CTA section',
            'Contact details — email, phone, address (Ranaghat, West Bengal)',
            'WhatsApp, Facebook, Instagram social links in footer',
            'URF Award recognition badge',
        ],
        'results'   => 'Mediascape now has a fully credentialed agency presence online — URF Award prominently featured, 10,000+ project history quantified, and a self-service pricing configurator that qualifies leads before they even reach out. The tiered package structure covers clients from ₹5,999 starter budgets up to ₹29,999 enterprise retainers.',
        'techStack' => ['WordPress', 'PHP', 'Custom Theme (CSS/JS)', 'JavaScript (Price Calculator)', 'WHatsApp API'],
        'screenshots' => [
            ['src' => 'assets/img/projects/mediascape-dma/screenshot-1.jpg', 'alt' => 'Mediascape — Homepage hero "India\'s Leading Digital Marketing Agency, URF Award"'],
            ['src' => 'assets/img/projects/mediascape-dma/screenshot-2.png', 'alt' => 'Mediascape — Full homepage with services, pricing, portfolio and testimonials'],
            ['src' => 'assets/img/projects/mediascape-dma/screenshot-3.png', 'alt' => 'Mediascape — Packages page with Social Media tiers, Custom Plan builder and Website packages'],
        ],
        'role'      => 'Designer and full-stack developer',
        'duration'  => '4 weeks',
    ],

    [
        'slug'      => 'restaurant-website-flavours-of-ranaghat',
        'priority'  => 70,
        'title'     => 'Restaurant Website & Reservation System',
        'category'  => 'Web',
        'status'    => 'Live',
        'client'    => 'Flavours of Ranaghat',
        'liveUrl'   => 'https://flavoursofranaghat.com',
        'cover'     => '',
        'summary'   => 'Premium dark-themed restaurant website for "Flavours of Ranaghat" — featuring an online table reservation system with seating area selection, Lunch & Dinner digital menus, signature dish showcase, and automated booking emails.',
        'problem'   => 'Flavours of Ranaghat — a restaurant in Ranaghat, West Bengal — was losing table bookings to competitors with online presence. All reservations came through phone calls, leading to missed bookings, no confirmation trail, and zero digital visibility for a venue that had multiple unique seating areas including a "Boat" section.',
        'solution'  => 'Designed and built a full premium restaurant website with a dark, elegant aesthetic matching the venue\'s ambiance. Implemented a dedicated Reservation page with a structured booking form capturing guest name, phone, number of persons, date, time slot (11 AM–10 PM), and seating area preference (Boat area selectable). Built a digital menu split into Lunch and Dinner sections. Added a signature dish spotlight for "Ilish er Rupsajja" to drive discoverability. Embedded a WhatsApp floating button for instant contact. Published key trust signals (200+ dishes, 250+ recipes, 15+ chefs, 20+ events) and a Strengths section (Hygienic Food, Fresh Environment, Skilled Chefs, Event & Party). Automated email confirmations sent on every booking.',
        'features'  => [
            'Online table reservation form — name, phone, persons, date, time, seating area',
            'Seating area selector (incl. signature "Boat" section)',
            'Automated booking confirmation emails',
            'Lunch & Dinner digital menus with "View Menu" links',
            '"Ilish er Rupsajja" signature dish spotlight section',
            'Our Strength section — Hygienic Food, Fresh Environment, Skilled Chefs, Event & Party',
            'Stats counters — 200+ Dishes, 250+ Recipes, 15+ Chefs, 20+ Events',
            'WhatsApp floating button for instant contact',
            '"Watch Our Video" promotional section',
            'Newsletter subscription — "Subscribe & Get 25% Off"',
            'Opening hours in header (Daily 11:00 AM – 10:00 PM)',
            'Contact details pinned in topbar and footer',
            'Social media links — Facebook, Instagram, Google Maps',
            'Mobile-first responsive dark-elegant design',
        ],
        'results'   => 'Restaurant went from zero digital presence to a fully branded online identity with a working reservation system. Phone-call friction for bookings was eliminated — guests can now book any seating area, any time, with automatic email confirmation. The signature dish and ambiance photography on the site communicate the premium experience effectively.',
        'techStack' => ['WordPress', 'PHP', 'Custom CSS', 'JavaScript', 'PHPMailer', 'WhatsApp API'],
        'screenshots' => [
            ['src' => 'assets/img/projects/flavours-of-ranaghat/screenshot-1.jpg', 'alt' => 'Flavours of Ranaghat — Homepage hero "Heaven of Flavours"'],
            ['src' => 'assets/img/projects/flavours-of-ranaghat/screenshot-2.png', 'alt' => 'Flavours of Ranaghat — Full website with menus, reservation and strengths'],
            ['src' => 'assets/img/projects/flavours-of-ranaghat/screenshot-3.png', 'alt' => 'Flavours of Ranaghat — Reservation page with booking form and seating area selector'],
        ],
        'role'      => 'Designer and full-stack developer',
        'duration'  => '3 weeks',
    ],
    [
        'slug'      => 'india-smm-panel',
        'featured'  => true,
        'priority'  => 10,
        'title'     => 'India SMM Panel',
        'category'  => 'Web',
        'status'    => 'Live',
        'client'    => 'IndiaSmmpanel.in',
        'liveUrl'   => 'https://indiasmmpanel.in',
        'cover'     => '',
        'summary'   => 'Commercial-grade SMM reseller platform handling 2.6M+ orders and 50,000+ users — fully automated via cron-based API workers, multi-gateway payments, and a real-time admin dashboard.',
        'problem'   => 'The client needed a self-running, high-throughput SMM reseller platform that could handle tens of thousands of concurrent orders without any manual fulfilment. Existing off-the-shelf scripts lacked the scalability, payment flexibility (UPI, Stripe, crypto), and API interoperability required to compete in the Indian market.',
        'solution'  => 'Designed and built indiasmmpanel.in from the ground up — an MVC-architected PHP application using Twig templating, MySQL at scale, and a cron-based background engine (sync.php) that automatically syncs orders with upstream SMM API providers. The system acts as both an API consumer (placing orders with providers) and an API provider (exposing endpoints to downstream resellers), enabling a full reseller chain. Dynamic markup calculation, live exchange-rate fetching, and multi-currency support were built in from day one.',
        'features'  => [
            'Automated cron-based order fulfilment (API v2 providers)',
            'Dual API mode — acts as client AND provider for resellers',
            'Multi-gateway payments: UPI, Stripe, Paytm, Coinbase, CoinPayments',
            'User wallet, balance top-up, and transaction history',
            'Real-time order status tracking with live AJAX updates',
            'Dynamic profit margin engine with live currency exchange rates',
            'Twig-compiled secure templating (zero code injection surface)',
            'Admin dashboard: user management, order management, ticket system',
            'Affiliate / referral system',
            'MySQL indexed for fast reads across 2.6M+ order records',
        ],
        'results'   => 'Platform reached 50,000+ registered users and processed over 2,604,000 completed orders with 99.9% uptime. The cron-based automation eliminated all manual fulfilment, and the dual API architecture enabled a downstream reseller network to run on top of the platform — effectively turning it into an API provider itself.',
        'techStack' => ['PHP 8.x', 'MySQL / MariaDB', 'Twig', 'Composer', 'JavaScript (ES6)', 'Linux Crontab', 'Bootstrap', 'UPI / Stripe / Crypto APIs'],
        'screenshots' => [
            ['src' => 'assets/img/projects/india-smm-panel/screenshot-1.jpg', 'alt' => 'India SMM Panel — Homepage hero with sign-in form'],
            ['src' => 'assets/img/projects/india-smm-panel/screenshot-2.png', 'alt' => 'India SMM Panel — Full page view'],
        ],
        'role'      => 'Full-stack developer & architect',
        'duration'  => '6 weeks',
    ],
    [
        'slug'      => 'trendbazar-print-on-demand',
        'featured'  => true,
        'priority'  => 60,
        'title'     => 'TrendBazar — Trending Fashion Store',
        'category'  => 'Ecommerce',
        'status'    => 'Live',
        'client'    => 'TrendBazar.in',
        'liveUrl'   => 'https://trendbazar.in',
        'cover'     => '',
        'summary'   => 'Full WooCommerce fashion ecommerce store featuring trending clothes, anime-inspired collections, custom print-on-demand designs, and pan-India delivery — built with a custom theme and advanced category management.',
        'problem'   => 'The client wanted a full-featured fashion ecommerce brand from scratch — one that could handle multiple niche product collections (trending, anime, verified, Valentine\'s), custom-printed apparel orders, and a growing catalogue without a bloated, slow platform.',
        'solution'  => 'Built TrendBazar on WooCommerce with a fully custom theme matching the brand\'s dark-navy and yellow identity. Implemented advanced category architecture to serve distinct collections (Trending Clothes, Anime Hub, Verified Clothes, Valentine\'s Day Special) from a single storefront. Integrated custom product design capabilities for print-on-demand, a live search with category filter, wishlist, comparison, and cart — all optimised for mobile-first shopping. Pan-India delivery with 7–8 day promise and easy returns communicated on-page.',
        'features'  => [
            'Custom WooCommerce theme — dark navy + yellow brand identity',
            'Multi-collection catalogue: Trending, Anime Hub, Verified Clothes, Valentine\'s Special',
            'Live search bar with category filter dropdown',
            'Wishlist, product comparison, and mini-cart in header',
            'Custom print-on-demand product type support',
            'Homepage hero slider with promotional banners',
            'Top Categories grid with icon tiles',
            'Trust badges: Premium Quality, Free Delivery 7–8 days, Easy Return, Pan India Delivery',
            'Newsletter subscription integration',
            'Mobile-first responsive design',
            'WooCommerce payment gateway (Razorpay / UPI)',
            'Social media links (Instagram, Facebook, Pinterest)',
        ],
        'results'   => 'Launched a complete fashion brand from zero — multiple product collections live, custom print-on-demand orders flowing, and full pan-India delivery infrastructure in place within 5 weeks. The distinct collection architecture (Anime Hub, Verified Clothes) creates strong niche SEO signals and repeat customer segments.',
        'techStack' => ['WordPress', 'WooCommerce', 'PHP', 'Custom Theme (CSS/JS)', 'Razorpay', 'Custom Plugins'],
        'screenshots' => [
            ['src' => 'assets/img/projects/trendbazar/screenshot-1.jpg', 'alt' => 'TrendBazar — Homepage header with search, categories and hero banner'],
            ['src' => 'assets/img/projects/trendbazar/screenshot-2.png', 'alt' => 'TrendBazar — Full storefront with product collections and footer'],
        ],
        'role'      => 'Designer, developer & integrations engineer',
        'duration'  => '5 weeks',
    ],
    [
        'slug'      => 'woocommerce-ecommerce-store',
        'featured'  => true,
        'priority'  => 50,
        'title'     => 'Arpisu — Nexva Fashion WooCommerce Store',
        'category'  => 'Ecommerce',
        'status'    => 'Live',
        'client'    => 'Nexva Trading PVT LTD',
        'liveUrl'   => 'https://arpisu.com',
        'cover'     => '',
        'summary'   => 'Full WooCommerce fashion store for Nexva Trading PVT LTD — "Style for Every You" — featuring 9 product categories, Summer Sale promotions up to 65% off, wishlist, worldwide free shipping, and a bold hot-pink brand identity.',
        'problem'   => 'Nexva Trading needed a complete online fashion retail presence from scratch — covering a broad catalogue (men\'s, women\'s, kids, ethnic, co-ord sets) with promotional campaign support, seasonal discounting, and a conversion-optimised shopping experience, without the bloat of template themes.',
        'solution'  => 'Built arpisu.com on WooCommerce with a fully custom hot-pink branded theme. Implemented a multi-category product architecture spanning 9 clothing segments. Added a homepage hero slider ("Style for Every You"), a "Perfect Dress for Every Occasion" feature banner, a Summer Sale promotional band (up to 65% off), and a grid of promotional tiles (2026 Latest Style, Accessories, Fun & Free, New Year New Trends). Integrated wishlist, cart count in nav, search, My Account, and newsletter signup. Set up worldwide free shipping and connected all social channels (X, Facebook, Pinterest, Instagram, LinkedIn, YouTube). Wrote store policy pages (Privacy, Refund & Returns, Terms, Shipping & Delivery).',
        'features'  => [
            'Custom WooCommerce theme — bold hot-pink brand identity (Nexva)',
            '9 product categories: Dresses, Ethnic Wear, Jeans, Kids Boys, Men, Party Wear, Suits & Salwar, Women\'s Co-Ord Sets, Women\'s Tops',
            'Homepage hero slider — "Style for Every You"',
            '"Perfect Dress for Every Occasion" feature section with View Offers CTA',
            'Summer Sale banner — Up to 65% Off with Shop Now CTA',
            'Promotional tile grid — Latest Style, Accessories (43% off), Fun & Free (35% off), New Year New Trends',
            'Product discount badges (up to 40% off) on shop listing cards',
            'Wishlist integration with live count in nav',
            'My Account, Sign In / Join with cart count',
            'Worldwide free shipping announced in topbar',
            'Newsletter signup with email input and GO button',
            'Full social media integration — X, Facebook, Pinterest, Instagram, LinkedIn, YouTube',
            'Complete policy pages — Privacy, Refund & Returns, T&Cs, Shipping & Delivery',
            'Fashion Stylist testimonial / brand quote section',
        ],
        'results'   => 'Launched a complete multi-category fashion brand online — 9 clothing segments live, seasonal promotions running (Summer Sale, New Year), and worldwide shipping enabled. The bold pink identity and promotional mechanics (percentage-off badges, sale banners) are designed to drive impulse purchases and repeat visits.',
        'techStack' => ['WordPress', 'WooCommerce', 'PHP', 'Custom Theme (CSS/JS)', 'Razorpay / Payment Gateway', 'Wishlist Plugin'],
        'screenshots' => [
            ['src' => 'assets/img/projects/arpisu-woocommerce/screenshot-1.jpg', 'alt' => 'Arpisu — Homepage hero "Style for Every You" with Nexva branding'],
            ['src' => 'assets/img/projects/arpisu-woocommerce/screenshot-2.png', 'alt' => 'Arpisu — Full homepage with Summer Sale banner, promotional tiles and footer'],
            ['src' => 'assets/img/projects/arpisu-woocommerce/screenshot-3.png', 'alt' => 'Arpisu — Shop page with 9 product categories and discount badges'],
        ],
        'role'      => 'Designer and full-stack developer',
        'duration'  => '4 weeks',
    ],
    [
        'slug'      => 'whatsapp-ai-chatbot-restaurant',
        'featured'  => true,
        'priority'  => 30,
        'title'     => 'WhatsApp AI Chatbot for Restaurants',
        'category'  => 'AI',
        'status'    => 'Live',
        'client'    => 'Restaurant (Demo)',
        'liveUrl'   => 'https://www.linkedin.com/posts/pramit-sarkar1_transform-your-business-with-our-whatsapp-activity-7391739385886507008-ARPe',
        'video'     => ['embed' => 'https://www.linkedin.com/embed/feed/update/urn:li:activity:7391739385886507008', 'title' => 'WhatsApp AI Chatbot for Restaurants — live demo on LinkedIn', 'link' => 'https://www.linkedin.com/posts/pramit-sarkar1_transform-your-business-with-our-whatsapp-activity-7391739385886507008-ARPe'],
        'cover'     => '',
        'summary'   => 'An AI-powered WhatsApp assistant that runs a restaurant\'s front desk 24/7 — answering menu, timing and location questions, taking table reservations, and capturing orders in natural conversation, with a live demo on LinkedIn.',
        'problem'   => 'Restaurants lose enquiries and bookings the moment staff are busy or off the clock. Every unanswered WhatsApp message about the menu, opening hours, or a table for the evening is a potential customer walking to a competitor. Owners needed a way to respond instantly, around the clock, without hiring extra staff to sit on the phone.',
        'solution'  => 'Built an AI chatbot on the WhatsApp Business API, orchestrated with n8n and powered by OpenAI, trained on the restaurant\'s menu, timings, seating, and policies. The bot understands free-form questions in plain language, answers instantly, guides guests through a table reservation, captures orders, and hands off to a human when a request falls outside its scope. Every conversation is logged so the owner keeps full visibility of enquiries and bookings.',
        'features'  => [
            'Runs directly inside WhatsApp — no app install for customers',
            'Natural-language menu, pricing, timing and location Q&A',
            'Guided table reservation flow (date, time, party size)',
            'Order capture with confirmation back to the customer',
            'Trained on the restaurant\'s own menu and policies',
            '24/7 instant response, even outside business hours',
            'Smart human handoff for out-of-scope requests',
            'Conversation logging for owner visibility',
            'Extendable to promotions, feedback and re-engagement',
        ],
        'results'   => 'The restaurant can now answer every WhatsApp enquiry instantly and convert casual questions into confirmed reservations without any staff intervention — demonstrated publicly in a LinkedIn walkthrough of the live conversation flow.',
        'techStack' => ['n8n', 'OpenAI (GPT-4o)', 'WhatsApp Business API', 'Webhooks', 'MySQL'],
        'screenshots' => [
            ['src' => 'assets/img/projects/whatsapp-ai-chatbot-restaurant/screenshot-1.svg', 'alt' => 'WhatsApp AI Chatbot for Restaurants — WhatsApp chat mock-up: the assistant answering a menu question and confirming a table reservation'],
        ],
        'role'      => 'AI automation engineer',
        'duration'  => '2 weeks',
    ],
    [
        'slug'      => 'spin-and-win-web-app',
        'priority'  => 90,
        'title'     => 'Spin & Win — Gamified Lead-Capture Web App',
        'category'  => 'Web',
        'status'    => 'Live',
        'client'    => 'TechDaddy',
        'liveUrl'   => 'https://techdaddy.net.in/spinwin',
        'video'     => ['embed' => 'https://www.linkedin.com/embed/feed/update/urn:li:activity:7418274048792526848', 'title' => 'Spin & Win web app — video demo on LinkedIn', 'link' => 'https://www.linkedin.com/posts/pramit-sarkar1_fullstackdeveloper-webdevelopment-gamification-activity-7418274048792526848-p-Zf'],
        'cover'     => '',
        'summary'   => 'A custom-coded "Spin the Wheel" web app that turns visitors into leads — an animated prize wheel with weighted odds, instant coupon codes, and a lead-capture form, built from scratch in PHP and JavaScript.',
        'problem'   => 'Static discount banners rarely convert. Businesses wanted an interactive, fun mechanic that would grab attention, collect contact details, and reward visitors with a coupon in a way that felt earned rather than given away — without paying for a bloated third-party marketing plugin.',
        'solution'  => 'Designed and built a self-contained gamification web app. Visitors enter their details, spin an animated wheel rendered on HTML5 Canvas, and win a prize decided by configurable weighted probabilities. Each win generates a unique coupon code, and every entry is stored as a lead. Prizes and odds are editable from a simple admin configuration, and the whole experience is mobile-first. A full video walkthrough is published on LinkedIn.',
        'features'  => [
            'Animated prize wheel built on HTML5 Canvas',
            'Weighted win probabilities configurable per prize',
            'Lead-capture form gating each spin',
            'Unique coupon-code generation on win',
            'One-spin-per-user control',
            'Admin-editable prizes, odds and messaging',
            'Fully mobile-responsive design',
            'Lightweight — no heavy plugins or frameworks',
        ],
        'results'   => 'A reusable engagement tool that captures leads while entertaining visitors — live at techdaddy.net.in/spinwin and demonstrated in a LinkedIn video showing the full spin-to-coupon flow.',
        'techStack' => ['PHP', 'JavaScript', 'HTML5 Canvas', 'CSS3', 'MySQL'],
        'screenshots' => [
            ['src' => 'assets/img/projects/spin-and-win-web-app/screenshot-1.png', 'alt' => 'Spin & Win — gamified prize-wheel lead-capture web app at techdaddy.net.in/spinwin'],
            ['src' => 'assets/img/projects/spin-and-win-web-app/screenshot-2.png', 'alt' => 'Spin & Win — full-length capture of the lead-capture entry screen before the prize wheel'],
        ],
        'role'      => 'Full-stack developer',
        'duration'  => '1 week',
    ],
    [
        'slug'      => 'techdaddy-tech-store',
        'priority'  => 100,
        'title'     => 'TechDaddy — Tech Shopping Platform',
        'category'  => 'Ecommerce',
        'status'    => 'Live',
        'client'    => 'TechDaddy',
        'liveUrl'   => 'https://techdaddy.net.in',
        'cover'     => '',
        'summary'   => 'A mobile-first online shopping platform for a wide range of tech products and accessories — with category browsing, product pages, cart and checkout, plus a gamified Spin & Win lead-capture module.',
        'problem'   => 'The client wanted a clean, fast, mobile-first storefront to sell tech products online — one that was easy to browse on a phone, simple to manage, and able to plug in marketing mechanics like coupons and giveaways to drive repeat visits.',
        'solution'  => 'Built TechDaddy as a full ecommerce store with a structured product catalogue, category navigation, product detail pages, cart and a streamlined checkout. The storefront is optimised for mobile shopping and is paired with a custom Spin & Win module (hosted at /spinwin) to capture leads and hand out discount coupons, tying marketing and sales together in one platform.',
        'features'  => [
            'Mobile-first tech products storefront',
            'Category and collection browsing',
            'Product detail pages with add-to-cart',
            'Cart and streamlined checkout flow',
            'Integrated Spin & Win coupon/lead module',
            'Clear terms, policy and support pages',
            'SEO-friendly page structure',
            'Responsive across phone, tablet and desktop',
        ],
        'results'   => 'Delivered a complete, self-manageable tech storefront with built-in marketing gamification — giving the client a single platform to both sell products and capture new leads.',
        'techStack' => ['WordPress', 'WooCommerce', 'PHP', 'JavaScript', 'MySQL'],
        'screenshots' => [
            ['src' => 'assets/img/projects/techdaddy-tech-store/screenshot-1.png', 'alt' => 'TechDaddy — tech shopping storefront homepage with product categories and offers'],
            ['src' => 'assets/img/projects/techdaddy-tech-store/screenshot-2.png', 'alt' => 'TechDaddy — full-length homepage capture with product categories, offers and footer'],
        ],
        'role'      => 'Designer and full-stack developer',
        'duration'  => '3 weeks',
    ],
    [
        'slug'      => 'depthroute-voip-platform',
        'priority'  => 80,
        'title'     => 'Depth Route — Business VoIP Platform',
        'category'  => 'Web',
        'status'    => 'Live',
        'client'    => 'Depth Route',
        'liveUrl'   => 'https://depthroute.com',
        'cover'     => '',
        'summary'   => 'A full marketing and product website for a business VoIP provider — presenting CLI/NCLI routes, SIP trunking, DID numbers, IVR, call analytics and global connectivity, with pricing, testimonials and lead-capture across multiple pages.',
        'problem'   => 'Depth Route offers enterprise-grade voice communication but needed a credible, conversion-focused website to explain complex telecom services (SIP trunking, DID management, CLI/NCLI routing) to non-technical buyers, build trust, and turn visitors into sales enquiries.',
        'solution'  => 'Designed and built a multi-page VoIP business website with a strong "crystal-clear calling" hero, clearly structured service sections (Voice Calling, DID Management, SIP Trunking, Caller ID & Branding, IVR & Automation, Analytics & Reporting), animated performance stats, a testimonials wall, pricing and multiple contact/lead paths. Full supporting pages — About, Contact, Terms & Conditions — were written and structured, with Cloudflare protection and email obfuscation in place.',
        'features'  => [
            'Service sections — Voice Calling, DID, SIP Trunking, IVR, Analytics',
            'Animated performance stat counters (uptime, users, countries)',
            'Client testimonials with verified-review styling',
            'Pricing and "Call Now / Start Free" conversion CTAs',
            'About, Contact and full Terms & Conditions pages',
            'Multi-region contact numbers (India + US)',
            'Cloudflare protection and email obfuscation',
            'Responsive, enterprise-grade dark UI',
        ],
        'results'   => 'Gave Depth Route a professional, trust-building web presence that clearly communicates a technical VoIP product to business buyers and channels visitors into sales enquiries across the site.',
        'techStack' => ['WordPress', 'PHP', 'Custom Theme (CSS/JS)', 'JavaScript', 'Cloudflare'],
        'screenshots' => [
            ['src' => 'assets/img/projects/depthroute-voip-platform/screenshot-1.png', 'alt' => 'Depth Route — VoIP platform homepage with "Professional VoIP Calling Solutions" hero'],
            ['src' => 'assets/img/projects/depthroute-voip-platform/screenshot-2.png', 'alt' => 'Depth Route — full-length homepage capture with service sections, stats and testimonials'],
        ],
        'role'      => 'Designer and full-stack developer',
        'duration'  => '3 weeks',
    ],
    [
        'slug'      => 'any-call-agency-dashboard',
        'priority'  => 170,
        'title'     => 'Any Call Agency — Management Dashboard',
        'category'  => 'Web',
        'status'    => 'Live',
        'client'    => 'Any Call Agency',
        'liveUrl'   => 'https://anycallagency.in',
        'cover'     => '',
        'summary'   => 'A web-based agency management platform with secure sign-in, account creation and a central dashboard for running day-to-day agency operations from one place.',
        'problem'   => 'The agency was juggling operations across spreadsheets and scattered tools. It needed a single, secure, login-protected web application where the team could manage its work from a central dashboard instead of disconnected files.',
        'solution'  => 'Built a management dashboard platform with user authentication (sign in / create account), a protected dashboard area, and a clean "Get Started" onboarding path. The application centralises the agency\'s operational data behind a secure login, giving the team one place to work from any device.',
        'features'  => [
            'Secure authentication — Sign In / Create Account',
            'Central management dashboard after login',
            '"Get Started" onboarding entry point',
            'Session-protected private area',
            'Clean, focused operations UI',
            'Responsive across desktop and mobile',
            'Structured, extendable backend',
        ],
        'results'   => 'Replaced scattered spreadsheets with a single, secure, login-protected dashboard — giving the agency one central system to manage its operations.',
        'techStack' => ['PHP', 'MySQL', 'JavaScript', 'Bootstrap'],
        'screenshots' => [
            ['src' => 'assets/img/projects/any-call-agency-dashboard/screenshot-1.png', 'alt' => 'Any Call Agency — management dashboard sign-in and get-started screen'],
            ['src' => 'assets/img/projects/any-call-agency-dashboard/screenshot-2.png', 'alt' => 'Any Call Agency — full-length capture of the dashboard sign-in / create-account screen'],
        ],
        'role'      => 'Full-stack developer',
        'duration'  => '3 weeks',
    ],
    [
        'slug'      => 'orbit-media-agency',
        'priority'  => 140,
        'title'     => 'Orbit Media — Creative & Digital Agency',
        'category'  => 'Web',
        'status'    => 'Live',
        'client'    => 'Orbit Media',
        'liveUrl'   => 'https://orbitmedia.co.in',
        'cover'     => '',
        'summary'   => 'A brand website for a creative and digital agency covering graphic design, branding and digital marketing — showcasing services, work and contact paths for prospective clients.',
        'problem'   => 'Orbit Media needed a polished online presence that would establish credibility, present its creative and digital-marketing services clearly, and turn visitors into enquiries — a digital storefront that reflected the quality of the studio\'s design work.',
        'solution'  => 'Designed and built an agency website with a strong visual identity, clearly structured service sections (graphic design, branding, digital marketing), a work/portfolio showcase, and prominent contact and enquiry CTAs. The site was built to load fast, look sharp on every device, and communicate the studio\'s creative strengths at a glance.',
        'features'  => [
            'Bold, design-led brand presentation',
            'Structured services showcase',
            'Portfolio / work highlights',
            'Clear contact and enquiry CTAs',
            'Fast-loading, mobile-first layout',
            'SEO-friendly page structure',
            'Consistent creative visual identity',
        ],
        'results'   => 'Gave the agency a credible, conversion-focused web presence that showcases its creative services and channels visitors toward enquiries.',
        'techStack' => ['WordPress', 'PHP', 'Custom Theme (CSS/JS)', 'JavaScript'],
        'screenshots' => [
            ['src' => 'assets/img/projects/orbit-media-agency/screenshot-1.png', 'alt' => 'Orbit Media — creative and digital agency website homepage'],
            ['src' => 'assets/img/projects/orbit-media-agency/screenshot-2.png', 'alt' => 'Orbit Media — full-length homepage capture of the creative and digital agency website'],
        ],
        'role'      => 'Designer and full-stack developer',
        'duration'  => '3 weeks',
    ],
    [
        'slug'      => 'premangshu-sarkar-workfolio',
        'priority'  => 150,
        'title'     => 'Premangshu Sarkar — Creative Workfolio',
        'category'  => 'Web',
        'status'    => 'Live',
        'client'    => 'Premangshu Sarkar',
        'liveUrl'   => 'https://premangshusarkar.com',
        'cover'     => '',
        'summary'   => 'A personal "workfolio" for a photographer, graphic designer and agency founder — presenting project case studies across multiple categories with a clean, gallery-driven layout and a booking CTA.',
        'problem'   => 'A multi-disciplinary creative — photographer, graphic designer and agency CEO — needed a single portfolio site to present a varied body of work professionally, organise it by category, and let prospective clients get in touch or book him directly.',
        'solution'  => 'Built a personal portfolio ("workfolio") site with an image-forward layout, project case-study pages (such as a website-redesign case study), category organisation (Agency, AI & ML, Consulting, Finance, Security, Technology and more), an about section and a clear "get in touch / book" call to action. The design keeps the visuals front and centre while staying fast and responsive.',
        'features'  => [
            'Image-forward, gallery-style layout',
            'Individual project case-study pages',
            'Work organised by category',
            'About / bio section',
            '"Get in touch / Book" contact CTA',
            'Fast-loading, mobile-first design',
            'Clean, minimal creative aesthetic',
        ],
        'results'   => 'Delivered a professional personal brand site that presents a diverse creative portfolio in one place and makes it easy for prospects to reach out and book.',
        'techStack' => ['WordPress', 'PHP', 'Custom Theme (CSS/JS)', 'JavaScript'],
        'screenshots' => [
            ['src' => 'assets/img/projects/premangshu-sarkar-workfolio/screenshot-1.png', 'alt' => 'Premangshu Sarkar — creative workfolio homepage'],
            ['src' => 'assets/img/projects/premangshu-sarkar-workfolio/screenshot-2.png', 'alt' => 'Premangshu Sarkar — full-length homepage capture of the creative workfolio'],
        ],
        'role'      => 'Designer and full-stack developer',
        'duration'  => '2 weeks',
    ],
    [
        'slug'      => 'the-prime-fitness-gym',
        'priority'  => 160,
        'title'     => 'The Prime Fitness — Gym & Fitness Website',
        'category'  => 'Web',
        'status'    => 'Live',
        'client'    => 'The Prime Fitness',
        'liveUrl'   => 'https://theprimefitness.in',
        'cover'     => '',
        'summary'   => 'A modern website for a local gym — presenting membership plans, training services, facilities and trainer information, with a clear join/enquiry call to action.',
        'problem'   => 'The gym relied on walk-ins and word of mouth and had no digital presence. It needed a website to showcase its facilities and membership options, build credibility with new prospects, and capture join enquiries online.',
        'solution'  => 'Designed and built a bold, energetic fitness website with a strong hero, membership/plan sections, training and facility highlights, and prominent "join now / enquire" CTAs. The site is mobile-first — most gym prospects arrive from a phone — and is structured to turn visitors into membership enquiries.',
        'features'  => [
            'Energetic hero with clear value proposition',
            'Membership plans and pricing sections',
            'Training services and facility highlights',
            'Join / enquiry call-to-action forms',
            'Location and contact details',
            'Mobile-first responsive design',
            'SEO-friendly local structure',
        ],
        'results'   => 'Took the gym from zero digital presence to a credible, mobile-first website that showcases its offering and captures membership enquiries online.',
        'techStack' => ['WordPress', 'PHP', 'Custom CSS', 'JavaScript'],
        'screenshots' => [
            ['src' => 'assets/img/projects/the-prime-fitness-gym/screenshot-1.png', 'alt' => 'The Prime Fitness — gym and fitness website homepage'],
            ['src' => 'assets/img/projects/the-prime-fitness-gym/screenshot-2.png', 'alt' => 'The Prime Fitness — full-length homepage capture of the gym and fitness website'],
        ],
        'role'      => 'Designer and full-stack developer',
        'duration'  => '2 weeks',
    ],
    [
        'slug'      => 'endoorthon-dental-store',
        'priority'  => 110,
        'title'     => 'Endoorthon — Dental Equipment Store',
        'category'  => 'Ecommerce',
        'status'    => 'Live',
        'client'    => 'Endoorthon',
        'liveUrl'   => 'https://endoorthon.in',
        'cover'     => '',
        'summary'   => 'An online store for professional dental equipment and endodontic/orthodontic products — with a full product catalogue, detailed product pages with ratings and reviews, membership, cart and checkout, promotional offers and WhatsApp support.',
        'problem'   => 'A dental-equipment supplier needed a professional online store to showcase and sell specialised endodontic and orthodontic devices to clinics and practitioners — with clear product information, pricing, reviews and a smooth checkout, instead of relying on offline enquiries.',
        'solution'  => 'Built a WooCommerce storefront tailored to dental professionals — a structured product catalogue with rich product pages (imagery, pricing, star ratings and reviews), a shop with search and category browsing, a membership/account area, cart and checkout, a site-wide promotional discount bar, and a floating WhatsApp button for quick pre-sales support. The design is clean and clinical, optimised for both desktop and mobile buyers.',
        'features'  => [
            'Dental / endodontic & orthodontic product catalogue',
            'Rich product pages with pricing, ratings and reviews',
            'Shop with search and category browsing',
            'Cart and streamlined checkout flow',
            'Membership / account area',
            'Site-wide promotional discount bar',
            'Floating WhatsApp support button',
            'Social links — Facebook, Instagram, YouTube, Pinterest, X',
            'Mobile-first responsive design',
        ],
        'results'   => 'Gave the supplier a credible online sales channel for specialised dental equipment — letting clinics and practitioners browse detailed product information, read reviews, and buy directly through a smooth WooCommerce checkout.',
        'techStack' => ['WordPress', 'WooCommerce', 'PHP', 'JavaScript', 'MySQL'],
        'screenshots' => [
            ['src' => 'assets/img/projects/endoorthon-dental-store/screenshot-1.png', 'alt' => 'Endoorthon — dental equipment online store homepage featuring the EndoMaster product'],
        ],
        'role'      => 'Designer and full-stack developer',
        'duration'  => '3 weeks',
    ],
    [
        'slug'      => 'megashop-online-store',
        'priority'  => 220,
        'title'     => 'MegaShop — Online Shopping Store',
        'category'  => 'Ecommerce',
        'status'    => 'Archived',
        'client'    => 'MegaShop',
        'liveUrl'   => 'https://web.archive.org/web/20230121142448/https://megashop.digital/',
        'cover'     => '',
        'summary'   => 'A multi-category online shopping store spanning electronics, fashion, home and kids products — an earlier ecommerce build, now preserved and viewable via the Web Archive.',
        'problem'   => 'The client wanted a broad, general-purpose online store that could carry many product categories under one roof and give shoppers a familiar, easy browsing and checkout experience.',
        'solution'  => 'Built a full ecommerce storefront with multi-category navigation, product listings and detail pages, cart and checkout, and a homepage designed around promotions and category discovery. The store covered diverse categories — electronics, fashion, home and kids — from a single platform.',
        'features'  => [
            'Multi-category product catalogue',
            'Product listing and detail pages',
            'Cart and checkout flow',
            'Promotional homepage layout',
            'Search and category browsing',
            'Responsive shopping experience',
            'Preserved via the Web Archive',
        ],
        'results'   => 'Delivered a complete general-purpose online store; the live site is no longer online, but the build is preserved and can be viewed through the Web Archive.',
        'techStack' => ['WordPress', 'WooCommerce', 'PHP', 'JavaScript', 'MySQL'],
        'screenshots' => [
            ['src' => 'assets/img/projects/megashop-online-store/screenshot-1.png', 'alt' => 'MegaShop — multi-category online shopping store homepage (archived, via Web Archive)'],
            ['src' => 'assets/img/projects/megashop-online-store/screenshot-2.png', 'alt' => 'MegaShop — full-length homepage capture of the online store (archived, via Web Archive)'],
        ],
        'role'      => 'Designer and full-stack developer',
        'duration'  => '4 weeks',
    ],
    [
        'slug'      => 'indian-watchdogs-portal',
        'priority'  => 250,
        'title'     => 'Indian Watchdogs — Awareness & Reporting Portal',
        'category'  => 'Web',
        'status'    => 'Archived',
        'client'    => 'Indian Watchdogs',
        'liveUrl'   => 'https://web.archive.org/web/20220903134928/https://indianwatchdogs.org/',
        'cover'     => '',
        'summary'   => 'A content-driven awareness and reporting portal — organising articles and information for the public, with a clean, readable, SEO-friendly structure. Now preserved via the Web Archive.',
        'problem'   => 'The project needed an information portal where content could be published and browsed easily by the public — readable, well-organised, and discoverable in search.',
        'solution'  => 'Built a content-management-driven portal with a clear article/information architecture, category navigation, readable typography, and an SEO-friendly page structure so content ranked and was easy to find. The layout prioritised fast reading and straightforward navigation.',
        'features'  => [
            'Article / content publishing structure',
            'Category-based navigation',
            'Clean, readable typography',
            'SEO-friendly page structure',
            'Search and browse',
            'Responsive reading experience',
            'Preserved via the Web Archive',
        ],
        'results'   => 'Delivered a functional public information portal; the live site is no longer online, but the build remains viewable through the Web Archive.',
        'techStack' => ['WordPress', 'PHP', 'MySQL', 'JavaScript'],
        'screenshots' => [
            ['src' => 'assets/img/projects/indian-watchdogs-portal/screenshot-1.png', 'alt' => 'Indian Watchdogs — awareness and reporting portal homepage (archived, via Web Archive)'],
            ['src' => 'assets/img/projects/indian-watchdogs-portal/screenshot-2.png', 'alt' => 'Indian Watchdogs — full-length homepage capture of the reporting portal (archived, via Web Archive)'],
        ],
        'role'      => 'Designer and full-stack developer',
        'duration'  => '3 weeks',
    ],
    [
        'slug'      => 'hax0r-tech-blog',
        'priority'  => 240,
        'title'     => 'Hax0r.tech — Cybersecurity & Tech Blog',
        'category'  => 'Web',
        'status'    => 'Archived',
        'client'    => 'Hax0r.tech',
        'liveUrl'   => 'https://web.archive.org/web/20240214213841/https://www.hax0r.tech/',
        'cover'     => '',
        'summary'   => 'A cybersecurity and technology blog publishing tutorials, guides and articles for a tech-savvy audience — built for fast reading and search discoverability. Now preserved via the Web Archive.',
        'problem'   => 'The project needed a dedicated blog to publish cybersecurity and tech content regularly, reach an audience through search, and present technical articles in a clean, readable format.',
        'solution'  => 'Built a blog platform with a content-first layout, category and tag organisation, code-friendly readable typography, and an SEO-optimised structure to grow organic traffic. The design kept articles front and centre while staying fast and responsive.',
        'features'  => [
            'Content-first blog layout',
            'Category and tag organisation',
            'Readable, code-friendly typography',
            'SEO-optimised article structure',
            'Search and related-post discovery',
            'Responsive reading experience',
            'Preserved via the Web Archive',
        ],
        'results'   => 'Delivered a working cybersecurity/tech publishing platform; the live site is no longer online, but the build is preserved through the Web Archive.',
        'techStack' => ['WordPress', 'PHP', 'MySQL', 'JavaScript', 'SEO'],
        'screenshots' => [
            ['src' => 'assets/img/projects/hax0r-tech-blog/screenshot-1.png', 'alt' => 'Hax0r.tech — cybersecurity and tech blog homepage (archived, via Web Archive)'],
            ['src' => 'assets/img/projects/hax0r-tech-blog/screenshot-2.png', 'alt' => 'Hax0r.tech — full-length homepage capture of the cybersecurity blog (archived, via Web Archive)'],
        ],
        'role'      => 'Designer and full-stack developer',
        'duration'  => '2 weeks',
    ],
    [
        'slug'      => 'crack4pc-download-portal',
        'priority'  => 230,
        'title'     => 'Crack4PC — Software Download Portal',
        'category'  => 'Web',
        'status'    => 'Archived',
        'client'    => 'Crack4PC',
        'liveUrl'   => 'https://web.archive.org/web/20240603011835/https://crack4pc.vip/',
        'cover'     => '',
        'summary'   => 'A high-volume software download and listing portal with a large catalogue, fast search, category browsing and heavily SEO-optimised listing pages built to scale traffic. Now preserved via the Web Archive.',
        'problem'   => 'The site needed to serve a very large catalogue of software listings, stay fast under high traffic, and rank in search for long-tail queries — which demanded a lean, SEO-first architecture and efficient listing pages.',
        'solution'  => 'Built a content-heavy download portal engineered for scale: a large, well-indexed catalogue, fast search and category browsing, templated and SEO-optimised listing pages, and a lightweight front end tuned for speed and organic discoverability. The structure was designed to handle a growing library of entries without slowing down.',
        'features'  => [
            'Large, indexed software catalogue',
            'Fast search and category browsing',
            'Templated, SEO-optimised listing pages',
            'Lightweight, high-speed front end',
            'Long-tail search optimisation',
            'Ad/monetisation-ready layout',
            'Preserved via the Web Archive',
        ],
        'results'   => 'Delivered a scalable, SEO-driven download portal capable of serving a large catalogue under heavy traffic; the live site is no longer online, but the build is preserved through the Web Archive.',
        'techStack' => ['WordPress', 'PHP', 'MySQL', 'JavaScript', 'SEO'],
        'screenshots' => [
            ['src' => 'assets/img/projects/crack4pc-download-portal/screenshot-1.png', 'alt' => 'Crack4PC — software download portal homepage (archived, via Web Archive)'],
            ['src' => 'assets/img/projects/crack4pc-download-portal/screenshot-2.png', 'alt' => 'Crack4PC — full-length homepage capture of the download portal (archived, via Web Archive)'],
        ],
        'role'      => 'Full-stack developer & SEO engineer',
        'duration'  => '3 weeks',
    ],
    [
        'slug'      => 'bongfest-cultural-events',
        'priority'  => 130,
        'title'     => 'Bong Fest — Cultural Event Management',
        'category'  => 'Web',
        'status'    => 'Live',
        'client'    => 'Bong Fest',
        'liveUrl'   => 'https://bongfest.org',
        'cover'     => '',
        'summary'   => 'A brand website for a Bengali cultural event-management collective — celebrating Bengal\'s art, music, food and traditions — with an events listing, a signature-events portfolio, an about/founder story, testimonials, a newsletter sign-up and a contact/enquiry flow.',
        'problem'   => 'Bong Fest curates cultural shows, music nights and community gatherings that celebrate Bengali heritage, but had no digital home to present its events, build credibility with attendees and partners, and capture enquiries for new events and collaborations.',
        'solution'  => 'Designed and built a vibrant, culture-forward website with an inviting hero ("Experience Bengal Like Never Before"), a dedicated upcoming-events listing with individual event detail pages, a signature-events portfolio gallery, an about section telling the founder\'s story, animated stat counters, a testimonials wall, a newsletter subscription and a full contact page with an enquiry form and map/address. The layout is mobile-first and built to turn visitors into event enquiries and sign-ups.',
        'features'  => [
            'Culture-led hero and brand storytelling',
            'Upcoming events listing with event detail pages',
            'Signature-events portfolio gallery',
            'About / founder story section',
            'Animated achievement stat counters',
            'Testimonials wall',
            'Newsletter subscription',
            'Contact page with enquiry form, phone, email and address',
            'Social links — Facebook, Twitter, Instagram, YouTube',
            'Mobile-first responsive design',
        ],
        'results'   => 'Gave Bong Fest a credible, culture-rich web presence that showcases its events and heritage, promotes upcoming gatherings, and channels attendees and partners into enquiries and newsletter sign-ups.',
        'techStack' => ['WordPress', 'PHP', 'Custom Theme (CSS/JS)', 'JavaScript'],
        'screenshots' => [
            ['src' => 'assets/img/projects/bongfest-cultural-events/screenshot-1.png', 'alt' => 'Bong Fest — Bengali cultural event-management website homepage with "Experience Bengal Like Never Before" hero'],
            ['src' => 'assets/img/projects/bongfest-cultural-events/screenshot-2.png', 'alt' => 'Bong Fest — full-length homepage capture with about, events portfolio, stats and testimonials'],
        ],
        'role'      => 'Designer and full-stack developer',
        'duration'  => '2 weeks',
    ],
    [
        'slug'      => 'b2b-local-lead-generation',
        'priority'  => 200,
        'title'     => 'B2B Local Lead Generation Service',
        'category'  => 'Automation',
        'status'    => 'Service',
        'client'    => 'Agencies & Local Businesses',
        'liveUrl'   => '',
        'cover'     => '',
        'summary'   => 'A city-wise B2B lead-generation service that delivers clean, structured contact lists for specific business categories (restaurant, gym, salon owners and more) — every record enriched with name, mobile, review count, rating, category, full address, website, email, geo-coordinates and location.',
        'problem'   => 'Agencies and local marketers need targeted, ready-to-use contact data to run outreach — but scraping, cleaning and geocoding thousands of business listings per city by hand is slow, error-prone and hard to scale across categories.',
        'solution'  => 'Built an automated lead-extraction pipeline that pulls business listings by category and city, cleans and de-duplicates the records, and enriches each one with the business name, mobile number, review count, rating, category, full address, website, email, precise latitude/longitude, state and location. Data is delivered as ready-to-import spreadsheets, priced on a simple flat per-city basis, and provided on a transparent non-exclusive licensing model.',
        'features'  => [
            'Category + city targeting (restaurants, gyms, salons, jewellery, mobile stores and more)',
            'Structured fields — name, mobile, review count, rating, category, address, website, email, latitude, longitude, state, location',
            'Automated extraction, cleaning and de-duplication',
            'Reputation signals (review count + rating) for prioritising outreach',
            'Geo-coordinates for mapping and territory planning',
            'Ready-to-import CSV / Google Sheets delivery',
            'Flat per-city pricing, transparent scope',
            'Non-exclusive licensing model',
            'Fast turnaround (typically 2–5 working days)',
        ],
        'results'   => 'Gives agencies an on-demand source of targeted, geocoded B2B contact lists per city — delivered ready to import into any CRM or outreach tool, without any manual data collection on their side.',
        'techStack' => ['Python', 'Web Scraping', 'Google Maps / Places API', 'Pandas', 'CSV / Google Sheets'],
        'screenshots' => [
            ['src' => 'assets/img/projects/b2b-local-lead-generation/screenshot-1.svg', 'alt' => 'B2B Local Lead Generation Service — sample geo-tagged restaurant lead list with masked mobile numbers, ratings and a map of mapped locations'],
        ],
        'sampleData' => [
            'label'      => 'Sample deliverable — restaurant leads across Kalyani & Krishnanagar, West Bengal',
            'note'       => 'A real preview slice in the exact column format delivered to clients (name, mobile, review count, rating, category, address, website, email, latitude, longitude, state, location). Phone numbers and email addresses are partly masked in this public sample; some cells are blank exactly as in the source data — clients receive the complete, unmasked dataset.',
            'columns'    => ['Name', 'Mobile Number', 'Review Count', 'Rating', 'Category', 'Address', 'Website', 'Email Id', 'Latitude', 'Longitude', 'State', 'Location'],
            'nameColumn' => 0,
            'mono'       => [1, 2, 3, 8, 9],
            'linkColumns' => [6],
            'rows'       => [
                ['ROYAL HUT RESTAURANT & CATERER', '9836••••67', '7237', '4.6', 'North Indian restaurant', 'ITI More Durga Puja Ground, B-16/19, A-B Connector, B 16, Block B, Kalyani, West Bengal 741235', 'http://www.royalhut.in/', '', '22.9801511', '88.4384402', 'West Bengal 741235', 'Kalyani'],
                ['Tris Planet - Hotel & Restaurant', '9007••••77', '1507', '4.3', 'Restaurant', 'Opposit: JIS College of Engineering, Block A5, Kalyani, West Bengal 741235', 'https://hoteltrisplanet.in/', 'in••@hoteltrisplanet.com', '22.9601629', '88.4485155', 'West Bengal 741235', 'Kalyani'],
                ['Chowman (Kalyani)', '9330••••30', '1217', '4.4', 'Chinese restaurant', 'beside of PNB Akshaya Branch, B 9, B9, Block B, Kalyani, West Bengal 741235', 'https://chowman.net/', '', '22.9792493', '88.4375053', 'West Bengal 741235', 'Kalyani'],
                ['BHOOTER RAJA DILO BOR KALYANI', '7278••••85', '1712', '3.9', 'Bengali restaurant', 'B-03/25(CA), B-5/25, B5, Block B, Kalyani, West Bengal 741235', 'https://bhooterrajadilobor.com/', 'ma••@bhooterrajadilobor.com', '22.9719284', '88.4323886', 'West Bengal 741235', 'Kalyani'],
                ['Baithaki', '9007••••62', '239', '4.2', 'North Indian restaurant', 'B-10/275, near Pannalal School, beside DEO Enterprise, Block B, Kalyani, West Bengal 741235', '', '', '22.9740697', '88.4403397', 'West Bengal 741235', 'Kalyani'],
                ['Rollacosta', '9804••••40', '3556', '4.1', 'Restaurant', 'B-9/11(CA, B 9, B9, Block B, Kalyani, West Bengal 741235', 'http://www.rollacosta.in/', '', '22.9784047', '88.436951', 'West Bengal 741235', 'Kalyani'],
                ['Mother\'s Hut', '9002••••99', '14099', '4.3', 'Restaurant', 'National Highway, beside Indian Oil Petrol Pump, 12, Bhatjangla, West Bengal 741102', 'http://www.mothershut.com/', '', '23.3699774', '88.4829466', 'West Bengal 741102', 'Bhatjangla'],
                ['Mommozi Krishnanagar', '9064••••81', '90', '4.7', 'Momo restaurant', '9 RN Tagore Road, High St, opposite Dhakeswari Bastralaya, Krishnanagar, West Bengal 741101', 'https://mommozi.com/', '', '23.411321', '88.4947265', 'West Bengal 741101', 'Krishnanagar'],
                ['Rannabati', '9609••••12', '1635', '3.8', 'Bengali restaurant', '64, Rabindra Nath Tagore Rd, Krishnanagar, West Bengal 741101', 'https://rannabatihsgroup.com/', '', '23.411719', '88.4946639', 'West Bengal 741101', 'Krishnanagar'],
                ['Adhar Chandra Das & Sons', '', '3558', '4.3', 'Sweet shop', '15, Ananta Hari Mitra Road, Nediarpara, Krishnanagar, West Bengal 741101', 'https://www.adharsweets.in/', 'in••@adharsweets.in', '23.4046079', '88.493992', 'West Bengal 741101', 'Krishnanagar'],
                ['Hangla Cafe and Family Restaurant', '8250••••65', '426', '4.2', 'Family restaurant', 'Sonda P, West Bengal 741103', 'http://www.hanglarestaurant.tech/', '', '23.4155844', '88.5282637', 'West Bengal 741103', 'Sonda P'],
            ],
        ],
        'role'      => 'Data engineer & lead-generation specialist',
        'duration'  => '2–5 working days',
    ],
    [
        'slug'      => 'edumanage-pro-school-lms',
        'priority'  => 180,
        'title'     => 'EduManage Pro — School Management System & LMS',
        'category'  => 'Web',
        'status'    => 'In Development',
        'client'    => 'In-house SaaS Product',
        'liveUrl'   => '',
        'githubUrl' => '',
        'cover'     => '',
        'summary'   => 'A comprehensive PHP school management platform with a built-in LMS — 24+ modules covering admissions, students, attendance, fees, exams, payroll, staff, communications and analytics, with role-based dashboards for six user types. Currently in active development.',
        'problem'   => 'Schools typically run on a patchwork of registers, spreadsheets and disconnected tools — admissions in one place, fee collection in another, attendance on paper, and no single view of the institution. Staff waste hours on manual data entry and reconciliation, parents are kept out of the loop, and administrators have no real-time picture of enrolment, fees due or attendance.',
        'solution'  => 'Building EduManage Pro as a single, self-hostable web application (designed to deploy on ordinary cPanel/Hostinger shared hosting) that runs the entire school from one dashboard. It uses a lightweight front-controller architecture (index.php → router → auto-discovered module actions) with session-based auth, bcrypt passwords, CSRF protection and six role-based access levels (Super Admin, Admin, Teacher, Student, Parent, Accountant). A web installer handles database setup, schema import, admin creation and config generation. Optional modules (Library, Timetable, Transport, Health, Discipline, Notice Board and more) can be toggled on or off from a Module Manager, and a daily cron drives automations such as absence alerts, overdue-fee marking, assignment reminders and weekly database backups.',
        'features'  => [
            'Role-based dashboards for 6 user types (Super Admin, Admin, Teacher, Student, Parent, Accountant)',
            'Online admissions with approval workflow and auto-enrolment',
            'Student directory with class/section management',
            'Attendance with bulk marking and automatic parent notifications on absence',
            'Fee structures, collection, receipts and overdue tracking',
            'Exam scheduling, marks entry and result publishing',
            'Built-in LMS — courses, lessons, assignments and submissions',
            'Payroll with salary structures and bulk payslip generation',
            'Staff directory, attendance and leave management',
            'Communications hub — in-app, email and SMS notifications with templates',
            'Analytics with Chart.js charts and leaderboards',
            'Toggleable optional modules (Library, Timetable, Transport, Health, Discipline, Notice Board and more)',
            'Automations via daily cron — overdue-fee marking, reminders, monthly summaries, weekly DB backup',
            'Web-based installer for one-step deployment on shared hosting',
        ],
        'results'   => 'Currently in active development. The core modules, role-based access system, web installer and cron-driven automations are being built and hardened toward a first production release.',
        'techStack' => ['PHP 8.1+', 'MySQL / MariaDB', 'Bootstrap 5.3', 'Chart.js', 'Apache (mod_rewrite)', 'Session Auth (bcrypt, CSRF, RBAC)'],
        'screenshots' => [
            ['src' => 'assets/img/projects/edumanage-pro-school-lms/screenshot-1.svg', 'alt' => 'EduManage Pro — school management dashboard concept showing student, fee and attendance stats with an attendance chart'],
        ],
        'role'      => 'Full-stack developer & architect',
        'duration'  => 'In development',
    ],
    [
        'slug'      => 'daily-linkedin-posts-pipeline',
        'featured'  => true,
        'priority'  => 40,
        'title'     => 'AI LinkedIn Content Engine — Auto-Posting Pipeline',
        'category'  => 'AI',
        'status'    => 'Live',
        'client'    => 'In-house Product',
        'liveUrl'   => '',
        'githubUrl' => 'https://github.com/Curious-Coderr/linkedin-autopilot',
        'cover'     => '',
        'summary'   => 'An end-to-end AI system that generates, designs and schedules a full day of LinkedIn content automatically — pulling trending topics, writing the posts, building carousel PDFs and infographics, and queueing everything to publish, with almost no human input. Now live and open-sourced on GitHub.',
        'problem'   => 'Staying consistently active on LinkedIn is brutal: it means finding fresh, relevant topics every day, writing posts that actually land, designing carousels and infographics, and then scheduling all of it on time. Done by hand it eats hours daily, and consistency collapses the moment you get busy — which is exactly when visibility matters most.',
        'solution'  => 'Building a multi-stage content pipeline (orchestrated with AI coding tools including the Antigravity IDE) that runs the whole workflow hands-free. Phase 1 fetches source material — trending Reddit threads, AI-news RSS feeds and a fresh data set for infographics. Phase 2 uses LLMs (via OpenRouter/Anthropic Claude) to generate the day\'s posts across several proven archetypes, governed by a written content doctrine and voice profile so everything stays on-brand. Phase 3 turns content into visual assets — 7-slide carousels rendered to PDF via Puppeteer, and HTML infographics screenshotted to PNG. Phase 4 delivers every asset to Slack for review, and Phase 5 drives browser automation to schedule the posts on LinkedIn across the coming days. The result is a repeatable, mostly autonomous "content factory".',
        'features'  => [
            'Automated topic sourcing from Reddit, AI-news RSS and live data sets',
            'AI-written posts across multiple high-performing archetypes',
            'On-brand output enforced by a content doctrine and voice profile',
            'Auto-generated 7-slide carousels rendered to PDF (Puppeteer)',
            'Auto-generated infographics (HTML → PNG screenshot)',
            'Performance engine that models posts on real LinkedIn analytics',
            'Slack delivery of all post text and visual assets for quick review',
            'Browser-automated LinkedIn scheduling across multiple days',
            'Configurable daily volume and posting cadence',
            'Built and iterated with AI coding assistants (Antigravity IDE)',
        ],
        'results'   => 'Now live and open-sourced on GitHub. The full pipeline — topic fetching, AI generation, carousel/infographic rendering, Slack delivery and browser-automated LinkedIn scheduling — runs end-to-end for hands-free daily posting.',
        'techStack' => ['Python', 'Node.js', 'Puppeteer', 'OpenRouter / Claude', 'Slack API', 'Antigravity IDE', 'Browser Automation'],
        'screenshots' => [
            ['src' => 'assets/img/projects/daily-linkedin-posts-pipeline/screenshot-1.svg', 'alt' => 'AI LinkedIn Content Engine — concept showing a scheduled LinkedIn post with an AI-built carousel and a fetch-to-schedule automation pipeline'],
        ],
        'role'      => 'AI automation engineer',
        'duration'  => '3 weeks',
    ],
    [
        'slug'      => 'local-seo-india-generator',
        'priority'  => 210,
        'title'     => 'Local SEO India — Programmatic Page Generator',
        'category'  => 'Automation',
        'status'    => 'In Development',
        'client'    => 'In-house Tool',
        'liveUrl'   => '',
        'githubUrl' => '',
        'cover'     => '',
        'summary'   => 'A programmatic SEO tool that generates thousands of city × keyword landing pages across every Indian state from a single HTML template — complete with SEO titles, meta descriptions, keyword-rich content and sitemaps — entirely offline and automated. Currently in active development.',
        'problem'   => 'Ranking for "keyword + city" searches at national scale means publishing hundreds or thousands of near-identical-but-localised landing pages — one per city, per keyword. Producing those by hand is impossible, and most tools that do it are expensive SaaS platforms or need external APIs and constant internet access.',
        'solution'  => 'Building a Python generator that takes one HTML template plus offline data sources — a full Indian cities/states JSON, keyword lists and CSV/text inputs — and produces an organised output tree of SEO-optimised pages (output/state-slug/keyword-slug-city-slug.html). It fills template placeholders for state, city, keyword, title, meta description, meta keywords and body content using built-in SEO helpers, slugifies everything cleanly, and shows the maximum possible variations (cities × keywords) before letting you generate all of them or a custom number. A batch mode with configurable pages-per-batch and delays keeps it usable on low-end PCs, with live progress, elapsed time and ETA, plus a companion sitemap splitter for large page sets.',
        'features'  => [
            'Generates city × keyword landing pages for every Indian state from one template',
            'Offline data sources — cities/states JSON, keyword files, CSV or plain text',
            'Auto SEO title, meta description, meta keywords and localised body content',
            'Clean slugified URL structure (state / keyword-city.html)',
            'Shows max possible variations, then generate all or a custom number',
            'Batch mode with configurable batch size and delays for low-end PCs',
            'Live status with elapsed time and ETA',
            'Companion sitemap splitter for very large page sets',
            'No external API or paid SaaS required — runs fully local',
        ],
        'results'   => 'Currently in active development. The template-driven generator, offline data ingestion, SEO helpers, batch mode and sitemap splitting are being built and refined toward a stable release.',
        'techStack' => ['Python', 'Jinja2', 'python-slugify', 'HTML / CSS', 'JSON / CSV data', 'Sitemap Generation'],
        'screenshots' => [
            ['src' => 'assets/img/projects/local-seo-india-generator/screenshot-1.svg', 'alt' => 'Local SEO India — concept showing a rank #1 local search result and a grid of auto-generated city landing pages'],
        ],
        'role'      => 'Developer & SEO automation engineer',
        'duration'  => 'In development',
    ],
    [
        'slug'      => 'agency-client-portal',
        'priority'  => 190,
        'title'     => 'AgencyOS — Digital Marketing Agency Management System',
        'category'  => 'Web',
        'status'    => 'In Development',
        'client'    => 'In-house SaaS Product',
        'liveUrl'   => '',
        'githubUrl' => '',
        'cover'     => '',
        'summary'   => 'An all-in-one internal management system for digital marketing agencies — clients, a visual content calendar, a public client-approval portal, invoicing, team roles, a credentials vault, AI caption generation and analytics, all in one PHP app. Currently in active development.',
        'problem'   => 'Digital marketing agencies juggle a dozen disconnected tools — spreadsheets for clients, one app for the content calendar, email threads for client approvals, separate invoicing software, and shared docs for passwords. Content gets approved over WhatsApp, credentials leak in plain text, invoices are chased manually, and nobody has a single source of truth for what is scheduled, approved or paid.',
        'solution'  => 'Building AgencyOS as a single self-hostable PHP/MySQL platform (designed for ordinary cPanel/hPanel shared hosting) that runs the whole agency from one dashboard. It ships with a first-run web installer that auto-creates all database tables and an admin account. Role-based access (Admin, Editor, Viewer) governs who can touch clients, content, invoices, the vault and team settings. The standout piece is a tokenised public client portal: each client gets a unique link (no login) where they review, approve or reject scheduled content and leave comments, with email notifications wired through PHPMailer/SMTP. A content calendar organises Reels, Stories, Carousels and Posts across Instagram, Facebook, YouTube and X, Gemini AI drafts captions on demand, and an AES-encrypted vault safely stores client credentials.',
        'features'  => [
            'Role-based access for Admin, Editor and Viewer users with per-client assignment',
            'First-run web installer that auto-creates tables and the admin account',
            'Client management with auto-generated portal links and welcome emails',
            'Public, login-free client portal to approve/reject content and comment',
            'Visual content calendar for Reels, Stories, Carousels and Posts',
            'Multi-platform content across Instagram, Facebook, YouTube and Twitter/X',
            'Approval workflow with status tracking and notifications',
            'Invoicing — create, view and manage client invoices',
            'Team management with roles and client-level permissions',
            'AES-encrypted credentials vault for client logins',
            'Gemini AI caption generation for posts',
            'Brand strategy editor and an analytics dashboard',
            'Media uploads (images/video) per client with configurable limits',
            'SMTP email (PHPMailer) with Gmail App Password support',
        ],
        'results'   => 'Currently in active development. The client portal, content calendar, approval workflow, invoicing, team roles, encrypted vault, AI captions and analytics are being built and hardened toward a first production release.',
        'techStack' => ['PHP 8.0+', 'MySQL / MariaDB', 'PHPMailer (SMTP)', 'Gemini AI', 'HTML / CSS / JavaScript', 'AES Encryption', 'Apache (cPanel/hPanel)'],
        'screenshots' => [
            ['src' => 'assets/img/projects/agency-client-portal/screenshot-1.svg', 'alt' => 'AgencyOS — digital marketing agency dashboard concept showing a content calendar, client approval portal and revenue stats'],
        ],
        'role'      => 'Full-stack developer & architect',
        'duration'  => 'In development',
    ],
    [
        'slug'      => 'dr-shyama-prasad-mukherjee-foundation',
        'priority'  => 120,
        'title'     => 'Dr. Shyama Prasad Mukherjee Foundation — NGO Website',
        'category'  => 'Web',
        'status'    => 'Live',
        'client'    => 'Dr. Shyama Prasad Mukherjee Foundation',
        'liveUrl'   => 'https://drshyamaprasadmukherjeefoundation.com/',
        'githubUrl' => '',
        'cover'     => '',
        'summary'   => 'A warm, trust-building website for a registered public charitable trust (established 2024) dedicated to education, healthcare and community welfare across India — with an emotive hero, activity showcase, founder story, an activities/blog feed, donation call-to-action and a contact flow.',
        'problem'   => 'A newly registered charitable trust needed a credible online home to tell its story, explain its grassroots work, build donor trust, share its latest activities and make it easy for supporters to reach out and contribute. Without a website, the foundation had no way to establish legitimacy, showcase its causes or convert visitors into donors and volunteers.',
        'solution'  => 'Designed and built a polished, mobile-first NGO website with an emotive hero slider ("Changing Lives Across India", "Empowering Every Child Through Education"), a clear four-pillar activities section (Education & Youth, Healthcare & Welfare, Women Empowerment, Skill Development), an inspiring founder-story section with a life-and-legacy timeline of Dr. Shyama Prasad Mukherjee, an activities & blog feed, animated impact stat counters, prominent donation and contact call-to-actions and a full contact section. Smooth scroll-reveal animations and an image slider give it a modern, credible feel that reassures donors and supporters.',
        'features'  => [
            'Emotive hero slider with rotating mission headlines',
            'Four-pillar activities showcase (Education, Healthcare, Women Empowerment, Skill Development)',
            'Founder story with a life-and-legacy timeline (1901 · 1934 · 1947)',
            'Activities & blog feed for latest initiatives and drives',
            'Prominent donation call-to-action for supporters',
            'Animated impact stat counters',
            'Contact section with enquiry details',
            'Scroll-reveal animations (AOS) and an image slider (Swiper)',
            'Fully responsive, mobile-first design',
            'SEO-friendly meta titles and descriptions',
        ],
        'results'   => 'Gave the foundation a credible, emotive digital presence that tells its story, showcases its grassroots causes, publishes its latest activities and channels visitors toward donations and enquiries — live at drshyamaprasadmukherjeefoundation.com.',
        'techStack' => ['HTML5', 'CSS3', 'JavaScript', 'Swiper.js', 'AOS (Animate On Scroll)', 'Font Awesome', 'Hostinger (LiteSpeed)'],
        'screenshots' => [
            ['src' => 'assets/img/projects/dr-shyama-prasad-mukherjee-foundation/screenshot-1.jpg', 'alt' => 'Dr. Shyama Prasad Mukherjee Foundation — homepage hero "Changing Lives Across India"'],
            ['src' => 'assets/img/projects/dr-shyama-prasad-mukherjee-foundation/screenshot-2.png', 'alt' => 'Dr. Shyama Prasad Mukherjee Foundation — full-length homepage capture with activities, founder story and donate CTA'],
        ],
        'role'      => 'Designer and front-end developer',
        'duration'  => '2 weeks',
    ],
];

/*
 * Order every project by editorial priority (lower number = higher value, shown first).
 * This drives the ordering on the homepage, the full projects page and the
 * prev/next case-study navigation. Projects without a priority sink to the bottom.
 */
usort($PROJECTS, static fn(array $a, array $b): int => ($a['priority'] ?? 9999) <=> ($b['priority'] ?? 9999));

$PROJECT_CATEGORIES = ['All', 'Web', 'Ecommerce', 'AI', 'Automation'];





/**
 * Find a single project by slug.
 */
function find_project(string $slug): ?array
{
    global $PROJECTS;
    foreach ($PROJECTS as $p) {
        if ($p['slug'] === $slug) {
            return $p;
        }
    }
    return null;
}

/**
 * The top flagship projects shown on the homepage.
 * These are the highest-value projects (`'featured' => true`), returned in
 * priority order and capped at 6 so the homepage always shows the best six.
 * Everything else lives on the full "All projects" page (projects.php).
 */
function get_featured_projects(int $limit = 6): array
{
    global $PROJECTS;
    $featured = array_values(array_filter($PROJECTS, static fn(array $p): bool => !empty($p['featured'])));
    return array_slice($featured, 0, $limit);
}
